# Keycloak user management CLI configuration file
#
# If an attribute has a default value, this value is used if the attribute is not
# set or empty.
#
# Environment variables can be used anywhere in this config file, simply surround
# them with ${}. For strings the variable must be within quotes (ie, "${STR_VAR}"),
# for numbers and booleans they should be plain (ie, ${INT_VAR}, ${BOOL_VAR})

[log]
## Log level
# Values: "debug", "info", "warn" or "error"
# Default: "info"
level = "${KCUSERS_LOG_LEVEL}"
## Log format
# Values: "json" or "text"
# Default: "text"
format = "${KCUSERS_LOG_FORMAT}"

[keycloak]
## Keycloak base URL
# Default: "http://localhost:8080"
authority = "${KCUSERS_AUTHORITY}"
# Keycloak realm
# Default: "test"
realm = "${KCUSERS_REALM}"
# Client ID
# Default: "test"
client_id = "${KCUSERS_CLIENT_ID}"
# Client secret
# Default: ""
client_secret = "${KCUSERS_CLIENT_SECRET}"
# Insecure TLS configuration
# Default: false
tls_insecure = ${KCUSERS_TLS_INSECURE}
# HTTP timeout
# Default: "5s"
timeout = "${KCUSERS_TIMEOUT}"
